frozen = [ "global_cov", "global_cov:log_amp", "global_cov:log_ls",]

[parameters]
vsini = 168.301
vz = 68.542
T = 1610.49
logg = 5.16

[metadata]
name = "SpectrumModel"
data = "Spectrum"
emulator = "/home/xchen/dopplerimg/starfish/BTSettl_K_emu"

[parameters.global_cov]
log_amp = 0.004698926464021468
log_ls = 9.997894754282289

[parameters.cheb]
1 = 0.131
2 = -0.151
