frozen = [ "global_cov", "global_cov:log_amp", "global_cov:log_ls",]

[parameters]
vsini = 24.665
vz = 111.826
T = 1398.811
logg = 4.935

[metadata]
name = "SpectrumModel"
data = "Spectrum"
emulator = "/home/xchen/dopplerimg/code/starfish/BTSettl_K_emu"

[parameters.global_cov]
log_amp = 0.00029794953639033757
log_ls = 0.5422117419640369

[parameters.cheb]
1 = -0.19
2 = 0.041
