frozen = [ "global_cov", "global_cov:log_amp", "global_cov:log_ls",]

[parameters]
vsini = 32.606
vz = 109.066
T = 1576.183
logg = 4.732

[metadata]
name = "SpectrumModel"
data = "Spectrum"
emulator = "/home/xchen/dopplerimg/starfish/BTSettl_K_emu"

[parameters.global_cov]
log_amp = 0.09644603925543363
log_ls = 0.021760293260712618

[parameters.cheb]
1 = -0.738
2 = 0.452
