frozen = []

[parameters]
vsini = 25
vz = 105
T = 1500
logg = 5.0

[metadata]
name = "SpectrumModel"
data = "Spectrum"
emulator = "/home/xchen/dopplerimg/code/starfish/BTSettl_K_emu"

[parameters.global_cov]
log_amp = 0
log_ls = 1

[parameters.cheb]
1 = 0
2 = 0
